name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/python
        with:
          command: pip install -r requirements.txt
  unit-test:
    name: "Run unit tests with coverage"
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/python
        with:
          command: pip install -r requirements.txt && coverage run --source=./janisbot4 -m unittest discover
      - uses: ./.github/actions/python
        with:
          command: coverage report -m --fail-under=90
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/python
        with:
          command: python -m flake8
  publish:
    name: "Publish to registry"
    needs:
      - build
      - unit-test
      - static-analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
      with:
        name: ${{ secrets.DOCKER_REGISTRY }}/janisbot4
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true